"use strict";
// Column headings and values in export files (English or Dutch, following
// the language of the admin interface).
const WORDS = {
  en: {
    received: "Received",
    status: "Status",
    language: "Language",
    email: "Email address",
    consent: "Consent",
    yes: "Yes",
    no: "No",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    registrations: "Registrations",
    usage: "Usage",
    environment: "Environment",
    reference: "Project reference",
    customer: "Customer",
    event: "Event",
    session: "Session",
    route: "Route",
    period: "Period",
    liveMinutes: "Live minutes",
    testMinutes: "Test minutes",
    streamMinutes: "Language stream minutes",
    gb: "GB (estimated)",
    peak: "Peak concurrent viewers",
    plays: "Plays",
    modules: "Modules",
    storage: "Storage",
    total: "Total",
    primary: "Primary",
    backup: "Backup",
  },
  nl: {
    received: "Ontvangen",
    status: "Status",
    language: "Taal",
    email: "E-mailadres",
    consent: "Toestemming",
    yes: "Ja",
    no: "Nee",
    pending: "In afwachting",
    approved: "Goedgekeurd",
    rejected: "Afgewezen",
    registrations: "Registraties",
    usage: "Gebruik",
    environment: "Omgeving",
    reference: "Projectreferentie",
    customer: "Klant",
    event: "Evenement",
    session: "Sessie",
    route: "Route",
    period: "Periode",
    liveMinutes: "Live minuten",
    testMinutes: "Testminuten",
    streamMinutes: "Taalstreamminuten",
    gb: "GB (geschat)",
    peak: "Max. gelijktijdige kijkers",
    plays: "Afspeelsessies",
    modules: "Modules",
    storage: "Opslag",
    total: "Totaal",
    primary: "Primair",
    backup: "Back-up",
  },
};
const exportWords = (lang) => WORDS[lang] || WORDS.en;

module.exports = { exportWords };
